esudo: false
branches:
  only:
  - master
language: node_js
node_js:
- '8'
before_install:
- git submodule update --init --recursive
#
# READIUM JS VIEWER
#
#- git fetch --all
#- for remote in `git branch -r | grep -v \> | grep -v master`; do git branch --track ${remote#origin/} $remote; done
- git branch -avv
- git remote -v
- git show-ref --heads
- git show-ref --head --hash head
- git branch -a --contains $(git rev-parse HEAD)
- git for-each-ref --format="%(refname:short) %(objectname)" 'refs/heads/' | grep $(git rev-parse HEAD) | cut -d " " -f 1
- git checkout `git for-each-ref --format="%(refname:short) %(objectname)" 'refs/heads/' | grep $(git rev-parse HEAD) | cut -d " " -f 1 | head -n1`
- git branch -avv
#
# READIUM JS
#
- cd readium-js
#
#- git fetch --all
- for remote in `git branch -r | grep -v \> | grep -v master`; do git branch --track ${remote#origin/} $remote; done
- git branch -avv
- git remote -v
- git show-ref --heads
- git show-ref --head --hash head
- git branch -a --contains $(git rev-parse HEAD)
- git for-each-ref --format="%(refname:short) %(objectname)" 'refs/heads/' | grep $(git rev-parse HEAD) | cut -d " " -f 1
- git checkout `git for-each-ref --format="%(refname:short) %(objectname)" 'refs/heads/' | grep $(git rev-parse HEAD) | cut -d " " -f 1 | head -n1`
- git branch -avv
#
# READIUM SHARED JS
#
- cd readium-shared-js
#
#- git fetch --all
- for remote in `git branch -r | grep -v \> | grep -v master`; do git branch --track ${remote#origin/} $remote; done
- git branch -avv
- git remote -v
- git show-ref --heads
- git show-ref --head --hash head
- git branch -a --contains $(git rev-parse HEAD)
- git for-each-ref --format="%(refname:short) %(objectname)" 'refs/heads/' | grep $(git rev-parse HEAD) | cut -d " " -f 1
- git checkout `git for-each-ref --format="%(refname:short) %(objectname)" 'refs/heads/' | grep $(git rev-parse HEAD) | cut -d " " -f 1 | head -n1`
- git branch -avv
- echo "plugins:['hypothesis']" > plugins/plugins.cson
- cat plugins/plugins.cson
#
# READIUM CFI JS
#
- cd readium-cfi-js
#
#- git fetch --all
- for remote in `git branch -r | grep -v \> | grep -v master`; do git branch --track ${remote#origin/} $remote; done
- git branch -avv
- git remote -v
- git show-ref --heads
- git show-ref --head --hash head
- git branch -a --contains $(git rev-parse HEAD)
- git for-each-ref --format="%(refname:short) %(objectname)" 'refs/heads/' | grep $(git rev-parse HEAD) | cut -d " " -f 1
- git checkout `git for-each-ref --format="%(refname:short) %(objectname)" 'refs/heads/' | grep $(git rev-parse HEAD) | cut -d " " -f 1 | head -n1`
- git branch -avv
#
- cd ../../../
install:
- npm run prepare:all
before_script:
- pwd
script:
- cd readium-js/readium-shared-js/readium-cfi-js
- npm run build
- npm run test:travis
- cd ../../..
- pwd
- git status
- npm run pretest:travis
- git status
- cd readium-js
- git status
- cd readium-shared-js
- git status
- cd readium-cfi-js
- git status
- cd ../../../
- cat build-output/version.json
before_deploy:
  - git config --local user.name heidarv
  - git config --local user.email heidarv@gmail.com
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key: 737fe9bc1cdab5cf8cd3f84322ef830e6ea17544
  file: dist/*
  skip_cleanup: true
  file_glob: true
after_success:
#- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ ${MODE} = "firefox" ] && npm install surge && echo "epub_content" > ./dist/cloud-reader/.surgeignore && surge --project ./dist/cloud-reader --domain readium.surge.sh'
#- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ ${MODE} = "firefox" ] && npm install firebase-tools && firebase deploy --non-interactive --token "$FIREBASE_TOKEN" --project "project-1351855251145549090"'
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ ${MODE} = "chromeApp" ] && node build-config/deployCrx.js'
after_failure: cat ./sauce_connect.log
env:
  global:
  - SAUCE_USERNAME=heidarv
  - SAUCE_ACCESS_KEY=55d5ae70-53c2-40a4-b34c-9d521e875ff2
  - USE_SAUCE=true
  - secure: nwpNZad60c5GglOpnesV6sggzsbCIbLg1ORHB2s347g3tIu3a7evbbToaDD/tsnnZsLHdR71hypCECRFMDORcmkx144lWRlquiGtvIcNb86jAR//QQtzLekFly9UAN6ublG0g5lvdjvBwxlPF1Jig+OMNR95BsnUxbmA8b5guIM=
  matrix:
  - MODE=chromeApp
#  - MODE=firefox
addons:
  sauce_connect:
    username: heidarv
    access_key: 55d5ae70-53c2-40a4-b34c-9d521e875ff2
